/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
    NavBar: typeof import('./src/components/NavBar/index.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
